from enum import Enum


class Team(Enum):
    ARG = "argentinos-juniors"
    BAN = "ca-banfield"
    BAC = "ca-barracas-central"
    BEL = "ca-belgrano-de-cordoba"
    BOC = "ca-boca-juniors"
    CCS = "ca-central-cordoba-de-santiago-del-estero"
    DYJ = "csd-defensa-y-justicia"
    EST = "club-estudiantes-de-la-plata"
    GLP = "gimnasia-y-esgrima-la-plata"
    GOD = "godoy-cruz-antonio-tomba"
    HUR = "ca-huracan"
    IND = "ca-independiente"
    INS = "instituto-ac-cordoba"
    IRI = "cs-independiente-rivadavia"
    LAN = "ca-lanus"
    NOB = "newells-old-boys"
    PLA = "ca-platense"
    RAC = "racing-club-de-avellaneda"
    RIE = "cd-riestra"
    RIV = "ca-river-plate"
    ROS = "ca-rosario-central"
    SAR = "ca-sarmiento"
    SLO = "ca-san-lorenzo-de-almagro"
    TAL = "ca-talleres-de-cordoba"
    TIG = "ca-tigre"
    TUC = "ca-tucuman"
    UNI = "ca-union-de-santa-fe"
    VEL = "club-atletico-velez-sarsfield"
